vim.keymap.set("n", "<Leader>e", vim.cmd.Ex)
vim.keymap.set("n", "<Leader>o", ":only<CR>")
vim.keymap.set("n", "<Leader>r", "<Esc>:edit<CR>")
vim.keymap.set("n", "<Leader>w", "<Esc>:write<CR>")
vim.keymap.set("n", "Q", "<Nop>")
