theme = "gruvbox_light"

[editor]
auto-save = true
color-modes = true
line-number = "relative"
rulers = [72, 80]
shell = ["bash", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = [
	"diagnostics",
	"position",
	"file-encoding",
	"position-percentage", 
	"file-type",
]

[keys.normal]
"\\" = { "w" = ":write", "q" = ":quit", "x" = ":write-quit-all!" }
