tap "homebrew/bundle"
tap "tshakalekholoane/taps"

brew "black"
brew "can"
brew "fd"
brew "fish"
brew "gcc"
brew "gh"
brew "git-lfs"
brew "gnupg"
brew "go"
brew "hyperfine"
brew "jq"
brew "lua-language-server"
brew "neovim"
brew "python"
brew "ripgrep"
brew "swiftformat"
brew "swiftlint"
brew "tmux"

cask "alacritty"
cask "arc"
cask "discord"
cask "github"
cask "notion"
cask "rectangle"
cask "virtualbox" if Hardware::CPU.intel?
cask "visual-studio-code"
